### ISSUE TITLE
Can't change alert file

### ISSUE THREAD

**Issue by akadevvy** [Bio2hazard/talis.xivplugin.twintania#16]
Plays sounds and countdowns fine but I can't change the alert file, the drop down menu doesn't drop down.. So Twisters is stuck to the phone ring and Divebombs are stuck on the ping sound..

**Comment by Bio2hazard** [comment]
The latest update should fix this. Could you grab it and confirm that everything works now?

**Comment by Dragedo** [comment]
i cant get the countdown or any other sounds to play anymore, was working fine up to 2 weeks ago.
updated to the newest version, installed the event plugin, even deleted the whole twintania plugin and reinstalled the newest version. no sounds working and the dropdown isnt working either. any clue whats wrong?

so, after hours of struggling and testing out everything i found... the solution was so easy it actually hurts..
i had the actualy ffxivapp folder on my E: drive, but certain things are saved in "Documents\FFXIVAPP"
after moving the mainfolder to that documents folder... SOUND
oh, and the dropdown for the alert file is also working

P.S.
whenever i hit the "RESET ALL SETTINGS TO THEIR DEFAULTS" button the value of "TwintaniaWidgetWidth" (file: Talis.XIVPlugin.Twintania.xml) changed to 2500 (im using dual screen) and i had to go back to specific file to manually set it back to 250 (after closing XIVAPP)

**Comment by akadevvy** [comment]
Newest update has fixed the issue, I can change the alert files now.. Thanks!

**Comment by ithorien** [comment]
I've tried everything anyone's posted about this issue, still can't get sound. What the hell.
